// One continuous stream of photos. No chapters, no segregation.
// Files are numbered 1..37 in this exact order.

export const photos = [
  { src: '1.jpg', cap: 'Golden hour, all of us' },
  { src: '2.jpg', cap: 'Before any of it' },
  { src: '3.jpg', cap: 'At his office' },
  { src: '4.jpg', cap: 'Under the lights' },
  { src: '5.jpg', cap: 'Garden afternoons' },
  { src: '6.jpg', cap: 'A brand new family' },
  { src: '7.jpg', cap: 'Dressed for a wedding' },
  { src: '8.jpg', cap: 'Both completely worn out' },
  { src: '9.jpg', cap: 'My sister and Papa' },
  { src: '10.jpg', cap: 'The underwater crew' },
  { src: '11.jpg', cap: 'Dressed up for Janmashtami' },
  { src: '12.jpg', cap: 'On safari' },
  { src: '13.jpg', cap: 'Me and Papa' },
  { src: '14.jpg', cap: 'The sangeet' },
  { src: '15.jpg', cap: 'Out on the water' },
  { src: '16.jpg', cap: 'Back home in Rajasthan' },
  { src: '17.jpg', cap: 'Putting up the decorations' },
  { src: '18.jpg', cap: 'The whole family' },
  { src: '19.jpg', cap: 'Caught mid hug' },
  { src: '20.jpg', cap: 'Just the two of them' },
  { src: '21.jpg', cap: 'Floor time' },
  { src: '22.jpg', cap: 'A day on the boat' },
  { src: '23.jpg', cap: 'Lost in the colour' },
  { src: '24.jpg', cap: 'Homework duty' },
  { src: '25.jpg', cap: 'All five of us' },
  { src: '26.jpg', cap: 'Just Papa' },
  { src: '27.jpg', cap: 'Always holding on' },
  { src: '28.jpg', cap: 'Slow hotel mornings' },
  { src: '29.jpg', cap: 'A family blessing' },
  { src: '30.jpg', cap: 'One of the little ones' },
  { src: '31.jpg', cap: 'Another celebration' },
  { src: '32.jpg', cap: 'The early days' },
  { src: '33.jpg', cap: 'Sweatshirts and old stone' },
  { src: '34.jpg', cap: 'With an old friend' },
  { src: '35.jpg', cap: 'On stage together' },
  { src: '36.jpg', cap: 'A rare night out' },
  { src: '37.jpg', cap: 'Off duty' },
];

// Four floating images behind the hero
export const heroCollage = [
  '1.jpg',
  '4.jpg',
  '8.jpg',
  '5.jpg',
];
