-- Run once in Supabase → SQL Editor → New query.
-- Same approach as the Sevven Star project: RLS left off so the
-- publishable anon key can read and insert freely.

create table if not exists public.birthday_wishes (
  id bigint generated by default as identity primary key,
  name text not null,
  relation text,
  message text not null,
  created_at timestamptz not null default now()
);

-- RLS intentionally disabled (matches the Sevven Star setup).
alter table public.birthday_wishes disable row level security;
